apiVersion: v1
kind: ConfigMap
metadata:
  name: config-domain
  namespace: knative-serving
data:
  # デフォルトで付与するドメイン
  example.com: ""
  # domain=devのラベルを持つrouteに付与するドメイン
  development.org: |
    selector: 
      domain: dev
  # domain=stgのラベルを持つrouteに付与するドメイン
  staging.org: |
    selector: 
      domain: stg


